sudo: required
language: node_js
dist: trusty
node_js:
- '8'
branches:
  except:
  - /^pr\\..*/"=
  - "/^features\\\\..*/"
before_install:
- git clone https://github.com/djanta/travis-npm-deploy.git ~/travis-npm-deploy
- chmod +x ~/travis-npm-deploy/deploy.sh && chmod +x ~/travis-npm-deploy/npm/*.sh
- bash ~/travis-npm-deploy/deploy.sh --git-config
install:
- bash ~/travis-npm-deploy/deploy.sh --install
- npm i --verbose
- 'echo "repo_token: $COVERALLS_REPO_TOKEN" > "./.coveralls.yml"'
- npm run snyk:login -- $SNYK_TOKEN
script:
- npm test
after_script:
- echo "Running after script"
after_success:
- npm run snyk:monitor
- npm run coverage
before_deploy:
- bash ~/travis-npm-deploy/deploy.sh login --user=$NPM_USER --password=$NPM_PWD --email=$NPM_EMAIL
deploy:
- provider: script
  skip_cleanup: true
  email: "$NPM_EMAIL"
  script: "~/travis-npm-deploy/deploy.sh"
  on:
    tags: true
    repo: djanta/djantajs-compiler-core
after_deploy:
- echo "Running after deploy step ..."
- bash ~/travis-npm-deploy/deploy.sh logout
notifications:
  email: false
  slack:
    rooms:
    - djantaio:1GeeSv1noSekK9to1yTqsbDw#travis-ci
    - djantaio:1GeeSv1noSekK9to1yTqsbDw#djantajs
    on_success: always
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch}
      by %{author} %{result} in %{duration}
  webhooks:
    urls:
    - "$WEBHOOK_GITTER"
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
  - secure: ickcXKuZP67QX3Tjua41BMBx6nsS5zqE9REDFwGGBu3PC8XO2ULXUu6Y1HeOwhx60iyPteVYxoyN1mLma3SnRBJLxbt9TIkJM4FxB0GWIc5HnCebTWcNk55Alf+4KKwb7a6CzabUhNf/iFDmOw/Qv32XUGFCqDhSAhREG7+/Ik4ufvvSuhGOyR1bgQrRlhYMZGf6OMpAhPRlrmJuV87J8aXrXIU8pTOrBNBMbnzFJBMapDwjNgAVswEA5bCssA+ayvJKmvPtNA4n7svvW2KItWn4kk6Mh/7G+qHjN9qUwbpQWDvJcQq2SBA3SI2t2STvRMy0YBjMOMxS/0n0vztb3JuZ8sclXRR+d+rVz5AnQX6Yk3MI01q0o88UdzlhnHrT1QLPTxGLKcbDipIrWUvXYpjt7NSFf2jd9if7j2bMbBtQhk3KVywFhkr4mygKC8FUklLIaq6X2y0TznPzQ7eprN5oSpvbiywAZVCAjNh/QZhBB4y/4f4EiphA3tMOaw5dyKJAQxFvzzFRWQpV03L9rXzTKzgs5sA00uwFO0SYmYrZES9O23v2In2Un/blgT9b+WGXNp6SbNYai3P9FpGk+85lWlhHgwQtXl+12n3S2l9anqtEkmqMzjuPyooddstQ7dmyz9aactOSdo+PB6HFTdBAJhiWgxixs2J9MtKmn/g=
  - secure: Wl9g5oJ9XWBESHj+GmcL+XGEhZB9uj10bRpiLi8yETNVj5Ilss/f8Ippw/9YgCZbYhB1E8zY2A52Pm0UzV5tpfEzw2yvgw/yvAFytlgVMM2fr8ouhhYZptVXIHhYhT7nTKxIh0I4nvXVRJzoX0KiN+q05cGykbfywUt4BBaSALR/Nf1o6Emxy7yuG04xA70lcK0DzGyYZIY20rnivtowZ4pL95S1wTLusxXEmTW93hphIQjPXk3mudeBQERmHoGU8iNy6d8w0ftEz0Giykcq7lq71OCyolUDgEgOYzj0uTlQeKugsSCqVhMdtKK3yLR+bwmeVr9zc2FXVprCACtn7MGDQ9TS/asalsTTs7j+Bcen3hL++M9AXDrEM0cdyZZmFeHPLa9USrzL7lTQxZi3fIyqswnv1o+nP4lym9SPbejxcTmYqpHb9KP98Xboj8FLsS/qJLN/t+rfdS19puxE3WbtB3/5O4vBumdw34ZLOLHQ8IAEjfbog+i5Sk1UFM90vQYAL/sqrLMv41GFLf/EyDy7+i+/Rl59rII2WGvwVO/qzoRl5Giyppn+yCrKoOK25zdgGmhZjxJ2nraxcL8FFCIfo72vPL4EmD2ILhVoUK8dmaLbsi3jWjvnjCH/JUMZOoNcC969biOnAyHGLakTqPnqnEUyruRsfL/L8THm0co=
  - secure: hhyuShE4DT6jYe6hnF7vIWcCJHLCYc2ZQf2w6UYLWy17w6L2Lozt937V3GXJob739yIYXcFPMx3Y/lhPM9+amjc+PygavynAXNUREoE30SodOzdY4DBqzyX1kPp+HZfaykxmJ0u6rDiitot0q9XVTFY2BZ2bwxA0J1p7GaYGzoBAP/AiuPeLVpoQUcv47kOMARK1OQXwalxh8SI+9lOp2ZOjHo230F4ZgHXlMDvdy+URJbmZHSfvj7kpPb8dqtaiwkpBKB12gmIbk+uKSsLPg6oDS235vhPqCRpxxlj1QRN2hXQeTGOKXPg2lQooYMJoTA5fi9sQi2uDtmvwUkTzcNBZeT71M36kxCWnAxtsRlp9fO/1m5R7U3ihM6O0GlMvUt2myyujqGyO7EoQlqzztu+XD02DEpw5mOlv9ULlaMdEVdB1jQKyLdnBtnkNSgmLWNNDf8W0OpqpxNoUzlYDLcKJ/zxHiHRfdjKdnsPwCQNQjDbBafRszrQnjZTau3LVTbbWlOtv3Q9NVgVnPYA8WM6oCmWOmH2GVqAMVSue//vXqx44TuWceLLEc9eEl4tkWpuHDZuw7FiolxxBWPo3Kzg1Kz6dPHfbNl0iH9oJsbsHaE/niiAGzI0BQphO9oB0I2hbJ7AH9Cv/9pwtQSLKJazC/IqFsRaWBFJ+ctT7pMQ=
  - secure: VHxNh3pZ8XK9vARRZgVgyaoODvpwLIjRZTV1i1/zDy/ddAA86rPD8j/6YYi/4us3JatXFEbGUltRgnj3z0b8LbbyI81BqyIcXNcOJI1Qy5Cj9u37g/nKNZpjPKwdHvqSgkujDr/f+oLXDZI3L9hXKq2NedFqviALmC7ZrFSql3lG6dJnjIv1Oao1thgKyu7od/uRbx+vJZutmxG8F5W88MjWy8cHnKasKJrA4cVSlI7ObgInsTiFZbBYubkBm3YG+OyZZ+M5oKODBJ2aK/KI0dWXym/0pjHu75PozMFObD83vny7nVUldErjPQ0r22dQNG+xPl8qa2iJNdiQfg3n9BT+benEb1iCGNPwhB0G/KA8iO4b5iuaOyNRgGzoB4QLZL/6uWeQBDEtk6C5hU4ltbg0CE73/lscmdSWHT+Ei4a0vUyzUxrqEgmK4hJGV969Td4/IngCPZtHny75tMMTbPvc3kN38D8nixjDOhp3PRr3bBbm5JtWMeZ1bn3nMyNSSi5/ymYdjbuMrOeBu9aUOTpzEadCBy4EyePhvqPJg0OQJOa0c4Owpm/c3MaHhm8r2Ri2PRur+t3n3+ecZtpTN4yvY0Uys/B/PiMiI5/HodG61Dwz2D+Ci+7gmZ+MTuiL8xqzTrX4aVkTCRIUzhkD75+D3nZvrM0S12FXjZ2I8Gc=
  - secure: F3TQvahqkRhpsxUr5pDFlb+s5bqs7+q4grVVCWM7lGlzA/2XmFie3IkiUyIcvW9eHQn4rc/ib9rl+Q6M7ScOj7tdh9H0kIeQ0+bTfRSO3YDAVvujk7rOH+GCEs4lci5QJpccB6mwl76zeLFDVmRoPPQ9+oCX1cp2NxZ1xGPm5pvFXKQZcW+C4IkSPCcPCLERQ+v06n6bJfoofGmhEqV13I7xtjz2oTkMGyLKIYjlJTvXqCvHKgjYeV4zy1vfZu9PX+75X03GWN+TbaX/yUCINi4bGKRmH14ZaN4FEaxq3OPXQKCPm7YWeZ+Pvyoha4BQW5ETFo95LURgmx/2B5GUzbHWSkPv4lkyuEyBYiWdaA3caaRfcFZ3Mja7XEjw7ko4BS6if+Qe8aCxq2B46naFinic1mIQ8QO5ed40rtV9nsGCrwPw0C/goTFsXHTF7JeOsDtC4HLXX0863IS5rL3dRmKglAq2dpXenMH+XQeeWIohJNvWqEiGgY8VOIdQrh1ggt9+3QVt5IhRg53pinsB+hJINxFWMOxfPZV0YWQTDHLmGtKDAFLxkJttPkXbqPNNbsYruzNs6rgUDsjmt4l6wwqValpHwRA1N/uls4VJw3pgXovfgrbXx305Rfp+Nkqn/GJmFgwuxWgZeIfDv/1sy99B7VmIX9rPT9tOl8HcpH0=
  - secure: qa7D3h6Vpm/Syo1R7ALMzDis2H311SOiAqFmMphIoN0Wc7ARCo37xmrsDL8Dr5AK6VrH1H2CHwLY5SvbLAnwc7wpMoxb6LzQkfXhxoi5OLD9aSNgetoyBbYDy8MHoRb2kHNOCaL8QlT9F6PKQXCOip18L9Wld7wP/1XMzW9+cnkLHTw3hXWSiklkqGc5Mnt6CAEsxpxEWmJmQiG6bFyXeY1uk/SddSBjmhNgQdbQZwv80oB5HvdF0lZK+ae1at6QThg86Ga8eoR7L3F1BK3sBwtOEXFn018TGbzHOWcv9A1z8xlwmyd8g7Yx2TUgac4eRdR4kS3d6QpyinP+QwBuiJSQ2w0CLK86t+ljZC3WOaFRk6RNfAWCsFhBJ2me1dPF7Nna7xGdTF8y4PXP2qBg4Phcz4by+t03r8QoMIb7oRrxfYNonk7wgCUKBOMIWslSfLz8mzmKEb5O7VMcpGPJH2HsZsbFlrXptToEo1omCUJ6MO6q214t1xPBcOvLNjm7qJbGM+iT/OCqWP3wIqhWq/wDvEmZxu+6o/IM9Ks10nv4URPFWCReh1ISjZwzYtYp0vRfTt5EcGDivhpMIT1rm9bqzbI9keqT8J0yKq6ziAlseDuMlotChqRf9N69iLWwctSUXGKHD4BzQ0eGP7mGUjhxpcGMSmNO4C9oxtsrobE=
  - secure: fdYdBLP8duOOIrro/xLHWjCINf0mlrb2rlG6Z9fyo1AWNSNfmCkW0N5dm0Yb5InyWDwtWaGkDbft7A2nsnAsK80ZywhDoesAKzwKwWSii2zSBbQnTY6PRov4JKG6hPLnEN/AQf/bD5tRlvWOlHUtmXSvex4a+pGIMfQHGw2cSNd/8NNmuihPyKAGp1uPJUSSJPLai0UjS0kGLr0onlC4gC/XyAT1duj6ZS5IHwwUOeN3U18Kl2+vi08V0HFKrEuH3MaRswwVdYx/AfRWsghlToveL1AHXMetos2miFkXhO6QV6bwepzWSZoepDD7oowhfGiiLeLMxwwXev6Mj8JPX3bYhQgLX1K5Cy+cVF4l8WSDrmEcfuQJrFMRX/koJy3kg8hh+UOb6/Cpcnj/c7av7s2KQfkhbtKhpasLQpsYIja1ZrMq9n9/j9n+m8ptGxushKkIq9u7NATtBPqffGmrX2gkBOhKBvWjdrE5u7yCAeLaVDxaNNzkdnjNWK1J7tH3+FtxV493FfNiw5vV2HOj2Vzq4HNSTlBkVodb/7XgLHDYSo8PgPVv4GVFszRDfVOdiZ8OvsTFqbGml+D60YFXuny42K4LspIsmnyJ9vdFyerzpt4OHHRLaXb4l/CDVz2/i438S+qEvarFyEdTiVfzTsiHUbsN8fbG4NlN4Z1X91s=
